zeus: Add missing camera blob
Xiaomi ships two blobs with the name libQnnHtpAltPrepV69Skel.so, one in
vendor/lib/rfsa/adsp and one in vendor/lib64/camera. We previously
missed the second one which lead to the first one being loaded which
fails with a signature verification error as shown below. Include both
libs to follow stock behaviour. This fixes grainy images when using
night mode in MiuiCamera.

E vendor.qti.camera.provider@2.7-service_64: vendor/qcom/proprietary/adsprpc/src/fastrpc_apps_user.c:1437: Error 0x80000406: remote_handle_open_domain: dynamic loading failed for file:///libQnnHtpAltPrepV69Skel.so?qnn_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3 (dlerror signature verify start failed for libQnnHtpAltPrepV69Skel.so) (errno Success)

Change-Id: I85822c4b46655c04969d2cd1fe33e99750343f74